project:
  type: website

website:
  title: "v8serialize"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    packaging:
      url: https://packaging.pypa.io/en/stable/


# tell quarto to read the sidebar file
metadata-files:
  - _sidebar.yml

quartodoc:
  style: pkgdown
  dir: reference
  title: Reference
  sidebar: "_sidebar.yml"
  package: v8serialize
  parser: numpy
  render_interlinks: true
  sections:
    - title: V8 Serialization format
      desc: Core `v8serialize` functionality.
      options:
        include_empty: true
        # dynamic: true
      contents:
        - path: 'encoding_decoding'
          kind: page
          summary:
            name: Encoding & Decoding
            desc: |
              `loads()` and `dumps()` read and write V8-serialized data.
          contents:
            - dumps
            - loads
            - Encoder
            - Decoder

        - path: 'customised_encoding'
          kind: page
          summary:
            name: Customized Encoding
            desc: |
              The `v8serialize.encode` module provides types to write V8 serialization format data.
          contents:
            - default_encode_steps
            - encode.serialize_object_references
            - encode.TagWriter
            - encode.DefaultEncodeContext
            - encode.WritableTagStream
            - encode.TagConstraintRemover
            - encode.HostObjectSerializer
        - path: 'customized_decoding'
          kind: page
          summary:
            name: Customized Decoding
            desc: |
              The `v8serialize.encode` module provides types to read V8 serialization format data.
          contents:
            - default_decode_steps
            - decode.TagReader
            - decode.DefaultDecodeContext
            - decode.ReadableTagStream
            - decode.ArrayReadResult
            - decode.ReferencedObject
            - decode.TagReaderRegistry
            - decode.read_stream

        - path: 'exceptions'
          kind: page
          summary:
            name: Exceptions
            desc: |
              Exceptions raised by `v8serialize`.
          contents:
            - V8SerializeError
            - DecodeV8SerializeError
            - EncodeV8SerializeError
            - UnhandledValueEncodeV8SerializeError
            - FeatureNotEnabledEncodeV8SerializeError
            - UnhandledTagDecodeV8SerializeError
            - IllegalCyclicReferenceV8SerializeError

        - path: 'types_protocols'
          kind: page
          summary:
            name: Types & Protocols
            desc: |
              Type annotations & Protocols used throughout `v8serialize`.
          contents:
            - constants.AnySerializationTag
            - constants.UnreleasedVersion
            - encode.HostObjectSerializerFn
            - encode.HostObjectSerializerObj
            - encode.HostObjectSerializer
            - encode.EncodeContext
            - encode.EncodeNextFn
            - encode.EncodeStepFn
            - encode.EncodeStepObject
            - encode.EncodeStep
            - decode.HostObjectDeserializerFn
            - decode.HostObjectDeserializerObj
            - decode.HostObjectDeserializer
            - decode.TagReader
            - decode.ReadableTagStreamReadFunction
            - decode.DecodeContext
            - decode.DecodeNextFn
            - decode.DecodeStepFn
            - decode.DecodeStepObject
            - decode.DecodeStep
            - decode.JSMapType
            - decode.JSSetType
            - decode.JSObjectType
            - decode.JSArrayType
            - decode.AnyJSError
            - decode.ArrayBufferConstructor
            - decode.ArrayBufferTransferConstructor
            - decode.ArrayBufferViewConstructor
            - decode.JSErrorBuilder
            - decode.SharedArrayBufferConstructor
            - decode.SharedArrayBufferId
            - decode.TransferId
            - Buffer
            - BufferSequence
            - ReadableBinary
            - SparseMutableSequence
            - SparseSequence

    - title: JavaScript types
      options:
        include_empty: true
      contents:
        - kind: page
          path: 'javascript_buffers'
          summary:
            name: ArrayBuffer, TypedArray, DataView
            desc: |
              Python equivalents of JavaScript's binary data buffer types.
          contents:
            - jstypes.JSArrayBuffer
            - jstypes.create_view
            - name: jstypes.JSTypedArray
              include_inherited: true
            - name: jstypes.JSDataView
              include_inherited: true
            - jstypes.DataViewBuffer
            - jstypes.DataFormat
            - jstypes.DataType
            - jstypes.ArrayBufferViewStructFormat
            - jstypes.JSArrayBufferError
            - jstypes.BoundsJSArrayBufferError
            - jstypes.ByteLengthJSArrayBufferError
            - jstypes.ItemSizeJSArrayBufferError
            - name: jstypes.JSInt8Array
              include_empty: false
            - name: jstypes.JSUint8Array
              include_empty: false
            - name: jstypes.JSUint8ClampedArray
              include_empty: false
            - name: jstypes.JSInt16Array
              include_empty: false
            - name: jstypes.JSUint16Array
              include_empty: false
            - name: jstypes.JSInt32Array
              include_empty: false
            - name: jstypes.JSUint32Array
              include_empty: false
            - name: jstypes.JSBigInt64Array
              include_empty: false
            - name: jstypes.JSBigUint64Array
              include_empty: false
            - name: jstypes.JSFloat16Array
              include_empty: false
            - name: jstypes.JSFloat32Array
              include_empty: false
            - name: jstypes.JSFloat64Array
              include_empty: false
            - jstypes.JSSharedArrayBuffer
            - jstypes.JSArrayBufferTransfer
        - kind: page
          path: 'javascript_date'
          summary:
            name: Date
            desc: |
              Python equivalent of [JavaScript's Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) is [](`datetime.datetime`).
          contents: []
        - kind: page
          path: 'javascript_error'
          summary:
            name: Error
            desc: |
              Python equivalents of JavaScript Error types.
          contents:
            - jstypes.JSErrorData
            - jstypes.JSError
        - kind: page
          path: 'javascript_map_set'
          summary:
            name: Map & Set
            desc: |
              Python equivalents of JavaScript's Map & Set types.
          contents:
            - jstypes.JSMap
            - jstypes.JSSet
        - kind: page
          path: 'javascript_object'
          summary:
            name: Object & Array
            desc: |
              Python equivalents of JavaScript's Object & Array types.
          contents:
            - jstypes.JSObject
            - jstypes.JSArray
            - jstypes.JSHole
        - kind: page
          path: 'javascript_primitives'
          summary:
            name: Primitives
            desc: |
              Python equivalents of JavaScript primitives that don't have a natural Python analogue.
          contents:
            - jstypes.JSUndefined
            - jstypes.JSPrimitiveObject
        - kind: page
          path: 'javascript_regexp'
          summary:
            name: RegExp
            desc: |
              Python equivalents of JavaScript RegExp type.
          contents:
            - jstypes.JSRegExp
        - kind: page
          path: 'javascript_utils'
          summary:
            name: Utilities
            desc: Functions associated with `v8codec.jstypes`.
          contents:
            - jstypes.js_repr_settings
            - jstypes.JSRepr
            - jstypes.JSReprSettingsNotRestored
            - jstypes.same_value_zero
            - jstypes.JSSameValueZero


    - title: Constants & Enums
      desc: V8 serialization format and JavaScript constants.
      contents:
        - kind: page
          path: api_constants
          summary:
            name: API Constants
            desc: Enums and constant values for `loads()`/`dumps()`
          contents:
            - name: SerializationFeature
              children: separate
            - SymbolicVersion
        - kind: page
          path: javascript_constants
          summary:
            name: JavaScript Constants
            desc: Enums and constant values for JavaScript types.
          contents:
            - name: JSErrorName
              include_empty: true
            - name: JSRegExpFlag
              include_empty: true
            - constants.FLOAT64_SAFE_INT_RANGE
            - constants.MAX_ARRAY_LENGTH
        - kind: page
          path: v8_constants
          summary:
            name: V8 Serialization Format Constants
            desc: |
              Enums and constant values for the V8 serialization format.
          contents:
            - constants.kLatestVersion
            - name: constants.SerializationTag
              include_empty: true
            - name: constants.ArrayBufferViewTag
              include_empty: true
            - name: constants.ArrayBufferViewFlags
              include_empty: true
            - name: constants.SerializationErrorTag
              include_empty: true
            - constants.TagConstraint
            - constants.JS_OBJECT_KEY_TAGS
            - constants.JS_CONSTANT_TAGS
            - constants.JS_ARRAY_BUFFER_TAGS
            - constants.JS_PRIMITIVE_OBJECT_TAGS
            - constants.JS_STRING_TAGS

    - title: HostObject Extensions
      desc: Platform-specific HostObject support.
      contents:
        - kind: page
          path: 'extensions_nodejs'
          summary:
            name: Node.JS Buffers
            desc: |
              Node.JS's custom Buffer HostObjects.
          contents:
            - extensions.NodeJsArrayBufferViewHostObjectHandler
            - extensions.serialize_js_array_buffer_views_as_nodejs_host_object
            - extensions.ViewFormat
            - extensions.NodeBufferFormat
            - extensions.NodeJsArrayBufferViewHostObjectHandlerDecodeError
